name: Terraform Deploy - Datadog + AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
          TF_VAR_datadog_site: ${{ secrets.DATADOG_SITE }}
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_external_id: ${{ secrets.DATADOG_EXTERNAL_ID }}
          TF_VAR_ec2_ssh_private_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          TF_VAR_ec2_user: ${{ secrets.EC2_USER }} 